insert into organizations (name, org_type, website_url, contact_text) values
  ('島根県', '県', 'https://www.pref.shimane.lg.jp/', '島根県 中小企業課'),
  ('しまね産業振興財団', '財団', 'https://www.joho-shimane.or.jp/', 'しまね産業振興財団 経営支援部'),
  ('松江市', '市町村', 'https://www.city.matsue.lg.jp/', '松江市 産業経済部 商工企業立地課'),
  ('浜田市', '市町村', 'https://www.city.hamada.shimane.jp/www/index.html', '浜田市 産業経済部 商工観光課'),
  ('出雲市', '市町村', 'https://www.city.izumo.shimane.jp/www/index.html', '出雲市 産業振興部 商工振興課'),
  ('益田市', '市町村', 'https://www.city.masuda.lg.jp/', '益田市 経済部 商工課'),
  ('大田市', '市町村', 'https://www.city.oda.lg.jp/', '大田市 産業振興部 商工観光課'),
  ('安来市', '市町村', 'https://www.city.yasugi.shimane.jp/', '安来市 産業振興部 商工観光課'),
  ('江津市', '市町村', 'https://www.city.gotsu.lg.jp/', '江津市 産業振興課'),
  ('雲南市', '市町村', 'http://www.city.unnan.shimane.jp/unnan/', '雲南市 商工観光課'),
  ('奥出雲町', '市町村', 'https://www.town.okuizumo.shimane.jp/', '奥出雲町 産業振興課'),
  ('飯南町', '市町村', 'https://www.iinan.jp/', '飯南町 産業振興課'),
  ('川本町', '市町村', 'https://www.town.shimane-kawamoto.lg.jp/', '川本町 産業振興課'),
  ('美郷町', '市町村', 'https://www.town.shimane-misato.lg.jp/', '美郷町 産業建設課'),
  ('邑南町', '市町村', 'https://www.town.ohnan.lg.jp/www/index.html', '邑南町 商工観光課'),
  ('津和野町', '市町村', 'https://www.town.tsuwano.lg.jp/www/index.html', '津和野町 産業建設課'),
  ('吉賀町', '市町村', 'https://www.town.yoshika.lg.jp/', '吉賀町 産業課'),
  ('海士町', '市町村', 'http://www.town.ama.shimane.jp/', '海士町 地産地商課'),
  ('西ノ島町', '市町村', 'https://www.town.nishinoshima.shimane.jp/', '西ノ島町 産業観光課'),
  ('知夫村', '市町村', 'http://www.vill.chibu.lg.jp/gyosei/', '知夫村 産業観光課'),
  ('隠岐の島町', '市町村', 'https://www.town.okinoshima.shimane.jp/www/index.html', '隠岐の島町 産業振興課');
