insert into subsidy_tags (subsidy_id, tag_id)
select s.id, t.id
from (values
  ('shimane-equipment-investment-2026','equipment'),
  ('shimane-equipment-investment-2026','manufacturing'),
  ('shimane-equipment-investment-2026','construction'),
  ('shimane-startup-support-2026','startup'),
  ('shimane-dx-support-2026','dx'),
  ('shimane-dx-support-2026','it'),
  ('shimane-energy-saving-2026','energy-saving'),
  ('shimane-business-succession-2026','business-succession'),
  ('joho-shimane-sales-channel-2026','sales-channel'),
  ('joho-shimane-product-development-2026','product-development'),
  ('joho-shimane-employment-2025','employment'),
  ('matsue-shokibo-jizoku-2026','sales-channel'),
  ('matsue-shokibo-jizoku-2026','equipment'),
  ('matsue-shokibo-jizoku-2026','retail'),
  ('matsue-shokibo-jizoku-2026','food-service'),
  ('matsue-startup-2026','startup'),
  ('matsue-startup-2026','other-industry'),
  ('matsue-akitenpo-2026','sales-channel'),
  ('matsue-akitenpo-2026','retail'),
  ('matsue-tourism-equipment-2026','tourism'),
  ('matsue-tourism-equipment-2026','equipment'),
  ('matsue-tourism-equipment-2026','hospitality-tourism'),
  ('izumo-it-dx-2026','dx'),
  ('izumo-it-dx-2026','it'),
  ('izumo-startup-2026','startup'),
  ('izumo-startup-2026','other-industry'),
  ('izumo-agri-equipment-2026','equipment'),
  ('izumo-agri-equipment-2026','agriculture-forestry-fisheries'),
  ('hamada-fishery-2026','equipment'),
  ('hamada-fishery-2026','agriculture-forestry-fisheries'),
  ('hamada-sales-channel-2026','sales-channel'),
  ('hamada-sales-channel-2026','other-industry'),
  ('hamada-akiya-migration-2026','migration'),
  ('hamada-akiya-migration-2026','housing'),
  ('hamada-akiya-migration-2026','other-industry'),
  ('masuda-startup-challenge-2026','startup'),
  ('masuda-startup-challenge-2026','other-industry'),
  ('masuda-equipment-2026','equipment'),
  ('masuda-equipment-2026','manufacturing'),
  ('masuda-employment-2025','employment'),
  ('masuda-employment-2025','other-industry'),
  ('oda-tourism-2026','tourism'),
  ('oda-tourism-2026','hospitality-tourism'),
  ('oda-akitenpo-2026','sales-channel'),
  ('oda-akitenpo-2026','retail'),
  ('yasugi-monozukuri-2026','equipment'),
  ('yasugi-monozukuri-2026','manufacturing'),
  ('gotsu-startup-2026','startup'),
  ('gotsu-startup-2026','other-industry'),
  ('unnan-business-succession-2026','business-succession'),
  ('unnan-business-succession-2026','other-industry'),
  ('okuizumo-agri-forestry-2026','equipment'),
  ('okuizumo-agri-forestry-2026','agriculture-forestry-fisheries'),
  ('tsuwano-migration-housing-2026','migration'),
  ('tsuwano-migration-housing-2026','housing'),
  ('tsuwano-migration-housing-2026','other-industry'),
  ('okinoshima-tourism-2026','tourism'),
  ('okinoshima-tourism-2026','hospitality-tourism'),
  ('ama-startup-2026','startup'),
  ('ama-startup-2026','other-industry')
) as m(subsidy_slug, tag_slug)
join subsidies s on s.slug = m.subsidy_slug
join tags t on t.slug = m.tag_slug;
